# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16k7g1iwIfie3Kj5t3jpBdBcnt5mWeh-K
"""

# # Autenticación Google Drive e instalación de librerías
# ####################################################################################
# from google.colab import drive; drive.mount('/content/drive')

!pip -q install flask
!pip install -q pycaret[full]
# !pip -q install pyngrok
# !ngrok config add-authtoken 2AddwGDdCS6m2JHw6vZtiHSsH22_7dM9jAq1ob1QqUH2hSLp6

################################### APP ############################################
import os
import pandas as pd
# from pyngrok import ngrok
from pycaret.classification import load_model, predict_model
from flask import Flask, render_template, request, send_from_directory

# template_folder='/content/drive/MyDrive/ENSA/Inspección al cortado/APP/templates'
modelo='./inpeccion_cortado_model'

app = Flask(__name__) # template_folder=template_folder

@app.route("/")
def index():
    return render_template("index.html")

@app.route('/upload', methods=['POST'])
def upload():

    current_directory = os.getcwd()

    file = request.files['archivo']
    url_file = os.path.join(current_directory, file.filename)
    file.save(url_file)

    df = pd.read_excel(url_file)
    modelo_entrenado = load_model(modelo)
    predict = predict_model(modelo_entrenado, data = df)
    predict.to_excel("resultados_inp_cortado.xlsx", index=False)

    return send_from_directory(directory=current_directory, path="resultados_inp_cortado.xlsx", as_attachment=True)

# ngrok_tunnel = ngrok.connect(5000)
# print('Aplicación Flask en:', ngrok_tunnel.public_url)
app.run()